name: Create Release
run-name: Create Release ${{github.ref_name}}

on: 
  workflow_dispatch:
    inputs:
      mod_version:
        description: 'Semantic Mod Version'
        required: true
      vintage_story_version:
        description: 'Vintage Story Version'
        required: true
      release_description: 
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Containerized Build
        uses: darkluke1111/vsmb@main
        with: 
          vs_version: ${{ github.event.inputs.vintage_story_version }}

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          release_name: ${{ github.event.inputs.mod_version }}
          tag_name: ${{ github.event.inputs.mod_version }}
          body: ${{ github.event.inputs.release_description }}
          #body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{env.RESULT}}
          asset_name: Terra_Prety_v${{ github.event.inputs.mod_version }}.zip
          asset_content_type: application/zip